# This file holds a list of scenarios to may be run.
# data_processing:
#   dataset_name: yahma/alpaca-cleaned
#   formatting: "instruct"
#   tokenize: True
#   input_field: input

data_processing:
  dataset_name: yahma/alpaca-cleaned
  chat_template: |
    {%- for message in messages %}
        {% if message['input'] != '' %}
    Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

        {% else %}
    Below is an instruction that describes a task. Write a response that appropriately completes the request.

        {% endif %}
    ### Instruction:
    {{ message['instruction'] }}

        {% if message['input'] != '' %}
    ### Input:
    {{ message['input'] }}

        {% endif %}
    ### Response:
    {{ message['output'] + eos_token }}
    {% endfor %}
  tokenize: True

scenarios:
    -   name: full-finetuning
        arguments:
            learning_rate: 2e-5
            model_name_or_path: 
                - 'mistralai/Mistral-7B-v0.1'
            torch_dtype: float16
